version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        - HTTP_PROXY=$http_proxy
    working_dir: ${WORKING_DIR}
    container_name: app_${CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ./:${WORKING_DIR}:consistent
      - /etc/hosts:/etc/hosts
      - $HOME/.ssh:/root/.ssh
    command: bash -c "npm i && npm run build-docker && npm audit fix"

  apache:
    build: docker/apache
    container_name: www_${CONTAINER_NAME}
    ports:
      - ${PORT_HTTPS}:${PORT_HTTPS}
    env_file:
      - .env
    volumes:
      - ./docker/apache/conf/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./:${WORKING_DIR}:ro
      - ./docker/apache/conf.cert/voxtecnologia.com.br.crt:/usr/local/apache2/conf/server.crt
      - ./docker/apache/conf.cert/voxtecnologia.com.br.key:/usr/local/apache2/conf/server.key
      - ./docker/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - app
    command: bash -c "httpd -DFOREGROUND"
